### PR TITLE
sched/wdog: fix signature for wdentry_t

### PR DESCRIPTION
**Pull request by bruenn**
gcc 8.2.1. doesn't allow lazy function pointer casting anymore. When building
px4-firmware 'make omnibus_f4sd_default' it complains:
wdog/wd_start.c:151:20: error: cast between incompatible function types from 'wdentry_t'

Changing the signature for wdentry_t will break cdcacm_rxtimeout(). To fix
this we use a va_list there.

Related to https://github.com/PX4/Firmware/issues/12283

### CODE REVIEW

**Comment by dagar** [comment]
Thanks @bruenn, we try to stay in sync with the upstream NuttX project. Could you contribute this to upstream NuttX (https://bitbucket.org/nuttx/nuttx/src/master/) and then we'll either backport the commit or pick it up the next time we upgrade.

**Comment by bruenn** [comment]
I send a bug report to upstream:
https://bitbucket.org/nuttx/nuttx/issues/159/sched-wdog-fix-signature-for-wdentry_t

**Comment by MaEtUgR** [comment]
I pushed a rebased version here: https://github.com/MaEtUgR/NuttX/tree/arm-gcc-9
To investigate further and get things running on ARM GCC 9 see https://github.com/PX4/Firmware/pull/13375

**Comment by MaEtUgR** [comment]
FYI when testing to compile on ARM GCC 9.2 with the latest NuttX version in use on master (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) I don't see this problem popping up anymore. I'm assuming it was fixed in upstream NuttX and we merged it since.
